
package org.tempuri;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CalcPrecoPrazoWSSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalcPrecoPrazoWSSoap {


    /**
     * 
     * @param sCdAvisoRecebimento
     * @param sDsSenha
     * @param sCepDestino
     * @param nVlLargura
     * @param nVlValorDeclarado
     * @param nVlComprimento
     * @param nCdEmpresa
     * @param nVlPeso
     * @param nCdFormato
     * @param sCdMaoPropria
     * @param sCepOrigem
     * @param nVlAltura
     * @param nCdServico
     * @param nVlDiametro
     * @return
     *     returns org.tempuri.CResultado
     */
    @WebMethod(operationName = "CalcPrecoPrazo", action = "http://tempuri.org/CalcPrecoPrazo")
    @WebResult(name = "CalcPrecoPrazoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrecoPrazo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazo")
    @ResponseWrapper(localName = "CalcPrecoPrazoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazoResponse")
    public CResultado calcPrecoPrazo(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        String nCdEmpresa,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        String sDsSenha,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        String sCepDestino,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        String nVlPeso,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        int nCdFormato,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlComprimento,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlAltura,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlLargura,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlDiametro,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        String sCdMaoPropria,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlValorDeclarado,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        String sCdAvisoRecebimento);

}
