
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CalcPrecoPrazoWS", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?WSDL")
public class CalcPrecoPrazoWS
    extends Service
{

    private final static URL CALCPRECOPRAZOWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.tempuri.CalcPrecoPrazoWS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tempuri.CalcPrecoPrazoWS.class.getResource(".");
            url = new URL(baseUrl, "http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CALCPRECOPRAZOWS_WSDL_LOCATION = url;
    }

    public CalcPrecoPrazoWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcPrecoPrazoWS() {
        super(CALCPRECOPRAZOWS_WSDL_LOCATION, new QName("http://tempuri.org/", "CalcPrecoPrazoWS"));
    }

    /**
     * 
     * @return
     *     returns CalcPrecoPrazoWSSoap
     */
    @WebEndpoint(name = "CalcPrecoPrazoWSSoap")
    public CalcPrecoPrazoWSSoap getCalcPrecoPrazoWSSoap() {
        return super.getPort(new QName("http://tempuri.org/", "CalcPrecoPrazoWSSoap"), CalcPrecoPrazoWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcPrecoPrazoWSSoap
     */
    @WebEndpoint(name = "CalcPrecoPrazoWSSoap")
    public CalcPrecoPrazoWSSoap getCalcPrecoPrazoWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "CalcPrecoPrazoWSSoap"), CalcPrecoPrazoWSSoap.class, features);
    }

}
