
package com.jogano10.web;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TemperatureConverterService", targetNamespace = "http://web.jogano10.com/", wsdlLocation = "http://localhost:8080/ws/TempConv?wsdl")
public class TemperatureConverterService
    extends Service
{

    private final static URL TEMPERATURECONVERTERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.jogano10.web.TemperatureConverterService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.jogano10.web.TemperatureConverterService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ws/TempConv?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ws/TempConv?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TEMPERATURECONVERTERSERVICE_WSDL_LOCATION = url;
    }

    public TemperatureConverterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TemperatureConverterService() {
        super(TEMPERATURECONVERTERSERVICE_WSDL_LOCATION, new QName("http://web.jogano10.com/", "TemperatureConverterService"));
    }

    /**
     * 
     * @return
     *     returns TemperatureConverter
     */
    @WebEndpoint(name = "TemperatureConverterPort")
    public TemperatureConverter getTemperatureConverterPort() {
        return super.getPort(new QName("http://web.jogano10.com/", "TemperatureConverterPort"), TemperatureConverter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TemperatureConverter
     */
    @WebEndpoint(name = "TemperatureConverterPort")
    public TemperatureConverter getTemperatureConverterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web.jogano10.com/", "TemperatureConverterPort"), TemperatureConverter.class, features);
    }

}
