
package com.jogano10.web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TemperatureConverter", targetNamespace = "http://web.jogano10.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TemperatureConverter {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "celsiusToFarenheint", targetNamespace = "http://web.jogano10.com/", className = "com.jogano10.web.CelsiusToFarenheint")
    @ResponseWrapper(localName = "celsiusToFarenheintResponse", targetNamespace = "http://web.jogano10.com/", className = "com.jogano10.web.CelsiusToFarenheintResponse")
    public double celsiusToFarenheint(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
