
package com.jogano10.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Singer", targetNamespace = "http://server.jogano10.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Singer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sing", targetNamespace = "http://server.jogano10.com/", className = "com.jogano10.client.Sing")
    @ResponseWrapper(localName = "singResponse", targetNamespace = "http://server.jogano10.com/", className = "com.jogano10.client.SingResponse")
    public String sing(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
